mile = float(input("Enter distance in miles: "))
effi = float(input("Enter efficiency in terms of MPG: "))
print(f"The total gallons of gas needed is {mile/effi}")
price = float(input("Enter price of 1 gallon of gas: "))
print(f"Total cost of gas is {(mile/effi)*price}")
